oro_user:
    settings:
        password_min_length:
            value: 2
        password_lower_case:
            value: false
        password_upper_case:
            value: false
        password_numbers:
            value: false
        password_special_chars:
            value: false
